sudo: false
language: node_js
node_js: stable
cache:
  directories:
    - $HOME/.npm
stages:
  - lint
  - test
jobs:
  include:
    - stage: lint
      script: npm run lint:js
      name: "Lint JS"
    - script: npm run lint:docker
      name: "Lint Dockerfile"
    - script: npm run lint:ec
      name: "Lint for editorconfig"
    - stage: test
      script: npm run test:js
      after_success: npm run coverage
